#!/usr/bin/env perl
use strict; use warnings;

# Copyright (C) 2010-2011 Dan Muresan
# Part of shut-audio-tools (http://danmbox.github.com/shut-audio-tools/)

my ($arg) = @ARGV; defined $arg or $arg="doc.txt";

sub printusage {
print <<EOF;
Usage: datetitle suffix.ext
  or:  datetitle { -h | --help | -? | --version }

Produces a filename containing the current date/time plus the suffix.

Report bugs at https://github.com/danmbox/shut-audio-tools/issues
EOF
  exit 0;
};

sub printversion {
  print <<EOF;
datetitle version 1.0
Copyright (C) 2010-2011 Dan Muresan
EOF
  exit 0;
}

printusage if (grep { "$_" eq "$arg" } "-h", "--help", "-?");
printversion if (grep { "$_" eq "$arg" } "--version");
my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime (time);
printf "%04d%02d%02d_%02d_%02d_%02d-%s\n",
  $year + 1900, $mon, $mday, $hour, $min, $sec, $arg;
